-- =========================================
-- firstname_lastname_exam.sql
-- SELECT Exam Practice
-- dvdrental database
-- =========================================


-- =========================================
-- Task 1
-- Customers living in California
-- =========================================

select
    c.first_name,
    c.last_name,
    c.email,
    ci.city
from customer c
join address a
    on c.address_id = a.address_id
join city ci
    on a.city_id = ci.city_id
where ci.city ilike '%california%'
order by c.last_name;


-- =========================================
-- Task 2
-- Films longer than 120 minutes
-- =========================================

select
    f.title,
    f.length,
    f.rating,
    c.name as category
from film f
join film_category fc
    on f.film_id = fc.film_id
join category c
    on fc.category_id = c.category_id
where f.length > 120
order by f.length desc
limit 10;


-- =========================================
-- Task 3
-- Total rentals per customer
-- =========================================

select
    cu.customer_id,
    cu.first_name,
    cu.last_name,
    count(r.rental_id) as total_rentals
from customer cu
join rental r
    on cu.customer_id = r.customer_id
join payment p
    on r.rental_id = p.rental_id
group by
    cu.customer_id,
    cu.first_name,
    cu.last_name
having count(r.rental_id) > 20
order by total_rentals desc;


-- =========================================
-- Task 4
-- Revenue generated by film category
-- =========================================

select
    cat.name as category,
    count(r.rental_id) as rental_count,
    round(sum(p.amount), 2) as total_revenue
from category cat
join film_category fc
    on cat.category_id = fc.category_id
join film f
    on fc.film_id = f.film_id
join inventory i
    on f.film_id = i.film_id
join rental r
    on i.inventory_id = r.inventory_id
join payment p
    on r.rental_id = p.rental_id
group by cat.name
having sum(p.amount) > 100
order by total_revenue desc;